In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("AI_Student_Life_India_2026.csv")

In [5]:
df.head(20)

,StudentID,Age,Gender,EducationLevel,City,AIToolUsed,DailyUsageHours,Purpose,ImpactonGrades,SatisfactionLevel
0,1,15,Female,School,Ludhiana,Grammarly,4.7,Research,Improved,Low
1,2,21,Female,College,Guwahati,ChatGPT,2.2,Learning,Improved,Medium
2,3,23,Female,University,Nagpur,Gemini,1.9,Writing,No Change,Low
3,4,24,Female,School,Visakhapatnam,Copilot,3.8,Coding,Improved,Low
4,5,16,Male,School,Gurugram,ChatGPT,4.8,Research,No Change,High
5,6,22,Female,College,Bhubaneswar,ChatGPT,3.0,Research,No Change,High
6,7,22,Male,University,Bhopal,Claude,6.4,Homework,No Change,Low
7,8,21,Female,University,Kanpur,Perplexity,4.6,Homework,No Change,High
8,9,25,Female,College,Lucknow,ChatGPT,3.4,Learning,Slight Decline,Low
9,10,22,Female,School,Thiruvananthapuram,Copilot,2.9,Homework,No Change,Low
10,11,22,Female,University,Ludhiana,Copilot,2.6,Writing,Improved,High
11,12,16,Female,School,Ranchi,Copilot,4.9,Learning,No Change,High
12,13,23,Male,University,Coimbatore,Grammarly,3.1,Learning,Slight Decline,Medium
13,14,17,Male,University,Delhi,Grammarly,0.9,Coding,Improved,Low
14,15,17,Female,School,Visakhapatnam,Copilot,2.9,Research,Slight Decline,Medium
15,16,21,Female,School,Bengaluru,Claude,4.9,Writing,Slight Decline,Medium
16,17,16,Male,College,Ranchi,ChatGPT,1.6,Homework,No Change,Low
17,18,23,Female,School,Thiruvananthapuram,Copilot,1.6,Coding,Improved,High
18,19,20,Female,College,Visakhapatnam,Perplexity,3.7,Learning,No Change,Low
19,20,25,Male,College,Indore,Gemini,3.7,Writing,Slight Decline,Low

In [6]:
df.shape

(5000, 10)

In [7]:
df.describe()

         StudentID          Age  DailyUsageHours
count  5000.000000  5000.000000      5000.000000
mean   2500.500000    19.910400         3.485000
std    1443.520003     3.166066         1.742666
min       1.000000    15.000000         0.500000
25%    1250.750000    17.000000         2.000000
50%    2500.500000    20.000000         3.500000
75%    3750.250000    23.000000         5.000000
max    5000.000000    25.000000         6.500000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          5000 non-null   int64
 1   Age                5000 non-null   int64
 2   Gender             5000 non-null   object
 3   EducationLevel     5000 non-null   object
 4   City               5000 non-null   object
 5   AIToolUsed         5000 non-null   object
 6   DailyUsageHours    5000 non-null   float64
 7   Purpose            5000 non-null   object
 8   ImpactonGrades     5000 non-null   object
 9   SatisfactionLevel  5000 non-null   object
dtypes: float64(1), int64(2), object(7)
memory usage: 390.8+ KB

In [5]:
df["City"].value_counts()

City
Lucknow               206
Jaipur                201
Mumbai                193
Vijayawada            190
Pune                  185
Ludhiana              182
Indore                182
Nagpur                181
Ranchi                178
Guwahati              176
Bhopal                176
Ahmedabad             174
Thiruvananthapuram    173
Coimbatore            172
Gurugram              171
Noida                 170
Mysuru                170
Chandigarh            167
Delhi                 167
Surat                 164
Kolkata               164
Bhubaneswar           162
Patna                 162
Visakhapatnam         160
Chennai               159
Kochi                 157
Hyderabad             154
Bengaluru             153
Kanpur                151
Name: count, dtype: int64

In [ ]:
1. Which students improved and how much was avg dailyusagehours
2. What is the breakdown of EducationLevel and Purpose?
3. Which AIToolUsed are used for what Purpose?
4. What are the total SUM DailyUsageHours broken down by Gender

In [ ]:
1. Those who improved had an average use of 3.48 daily hours
2. Equal distribution of Educational Level using it for all purposes
3. Claude and Perplexity lead Writing (161)
   Grammarly lead Coding(158)
   NotionAI and Copilot lead Learning (157, 156)
   Gemini and Copilot lead Homework (156, 155)
4. Females have total: 9056 hours   Males have total: 8368 hours